---
# tasks file for haproxy
- name: Install load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: present

- name: Configure "{{ payload }}" load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

- name: Enable Haproxy
  service:
    name: "{{ payload }}"
    state: started
    enabled: true
