---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  template:
    dest: /etc/yum.repos.d/internal_three-tier-app.repo
    src: repos_template.j2
    mode: 0644

- name: install base tools and packages
  yum:
    name:
      - python-pip
    state: latest
